version: '3'
services:
  app:
    build: .
    ports:
      - "8080:80"
    depends_on:
      - db
  db:
    image: postgresql:5.7
    environment:
        image: postgres
        restart: always
        user: postgres
  apache:
    image: httpd:2.4
    ports:
      - "8081:80"
    volumes:
      - ./apache/httpd.conf:/usr/local/apache2/conf/httpd.conf  
    depends_on:
      - app
 
  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./path/to/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app

