version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - db
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: dockerdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Vinithk1234$
    volumes:
      - pg_data:/var/lib/postgresql/data
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 5432
      PMA_USER: postgres
      PMA_PASSWORD: Vinithk1234

volumes:
  pg_data:
